server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-campus-toutiao?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis:
  mapper-locations: classpath*:com/campusToutiao/CampusToutiaoEE/dao/**/*.xml